# Generated by Django 6.0.6 on 2026-06-12 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True, verbose_name='Tanggal Run')),
                ('run_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp Run')),
                ('total', models.IntegerField(default=0, verbose_name='Total Lokasi')),
                ('verified', models.IntegerField(default=0, verbose_name='Verified')),
                ('duplicate', models.IntegerField(default=0, verbose_name='Duplicate')),
                ('suspended', models.IntegerField(default=0, verbose_name='Suspended')),
                ('unverified', models.IntegerField(default=0, verbose_name='Verification Required')),
            ],
            options={
                'verbose_name': 'Fetch Run',
                'verbose_name_plural': 'Fetch Runs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LocationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Kode Kios')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='Location ID')),
                ('business_name', models.CharField(blank=True, max_length=255, verbose_name='Nama Bisnis')),
                ('account_name', models.CharField(blank=True, max_length=255, verbose_name='Account Name')),
                ('address', models.TextField(blank=True, verbose_name='Alamat')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('coord_status', models.CharField(choices=[('OK', 'OK'), ('MISSING', 'Missing'), ('PARSE_ERROR', 'Parse Error'), ('OUT_OF_RANGE', 'Out of Range')], default='MISSING', max_length=20, verbose_name='Status Koordinat')),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Duplicate', 'Duplicate'), ('Suspended', 'Suspended'), ('Verification Required', 'Verification Required')], db_index=True, max_length=50, verbose_name='Status Verifikasi')),
                ('has_vom', models.BooleanField(default=False, verbose_name='Has Voice of Merchant')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Is Duplicate')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Is Suspended')),
                ('has_pending_edits', models.BooleanField(default=False, verbose_name='Has Pending Edits')),
                ('maps_uri', models.TextField(blank=True, verbose_name='Google Maps URI')),
                ('fetched_at', models.DateTimeField(verbose_name='Waktu Fetch')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='gbp.fetchrun', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Location Snapshot',
                'verbose_name_plural': 'Location Snapshots',
                'indexes': [models.Index(fields=['run', 'status'], name='gbp_locatio_run_id_d79c86_idx'), models.Index(fields=['store_code'], name='gbp_locatio_store_c_fd2abb_idx')],
            },
        ),
    ]
