# Generated by Django 6.0.6 on 2026-06-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Kode Kios / Store Code')),
                ('location_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Location ID / Nama Lokasi')),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Nama Bisnis')),
                ('network_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Network')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Name')),
                ('verification_status', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Status Verifikasi')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Disinkronkan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Location',
                'verbose_name_plural': 'Master Locations',
                'db_table': 'gbp_masterlocation',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Job')),
                ('source_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipe Sumber')),
                ('source_label', models.CharField(blank=True, max_length=500, null=True, verbose_name='Label Sumber')),
                ('total_master', models.IntegerField(default=0, verbose_name='Total Master')),
                ('total_api', models.IntegerField(default=0, verbose_name='Total API')),
                ('total_matched', models.IntegerField(default=0, verbose_name='Total Matched')),
                ('total_updated', models.IntegerField(default=0, verbose_name='Total Updated')),
                ('total_unchanged', models.IntegerField(default=0, verbose_name='Total Unchanged')),
                ('total_not_found_master', models.IntegerField(default=0, verbose_name='Tidak Ditemukan di Master')),
                ('total_not_found_api', models.IntegerField(default=0, verbose_name='Tidak Ditemukan di API')),
                ('total_invalid', models.IntegerField(default=0, verbose_name='Total Invalid')),
                ('total_manual_review', models.IntegerField(default=0, verbose_name='Total Manual Review')),
                ('total_error', models.IntegerField(default=0, verbose_name='Total Error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Job',
                'verbose_name_plural': 'Reconciliation Jobs',
                'db_table': 'gbp_reconciliationjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Store Code')),
                ('network_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Network Name')),
                ('business_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Nama Bisnis')),
                ('location_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Location Name')),
                ('identifier_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nilai Identifier')),
                ('match_rule', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aturan Matching')),
                ('old_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Lama')),
                ('new_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Baru')),
                ('process_status', models.CharField(choices=[('Updated', 'Updated'), ('Unchanged', 'Unchanged'), ('Not Found in Master', 'Not Found in Master'), ('Not Found in API', 'Not Found in API'), ('Invalid', 'Invalid'), ('Manual Review', 'Manual Review'), ('Error', 'Error'), ('Matched', 'Matched'), ('Not Found', 'Not Found')], db_index=True, max_length=100, verbose_name='Status Proses')),
                ('status_changed', models.BooleanField(db_index=True, default=False, verbose_name='Status Berubah?')),
                ('change_note', models.TextField(blank=True, null=True, verbose_name='Catatan Perubahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reconciliation Result',
                'verbose_name_plural': 'Reconciliation Results',
                'db_table': 'gbp_reconciliationresult',
            },
        ),
        migrations.AddField(
            model_name='fetchrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='locationsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Bisnis'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Fetch'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location ID'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='maps_uri',
            field=models.TextField(blank=True, null=True, verbose_name='Google Maps URI'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='store_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Kode Kios'),
        ),
        migrations.AddIndex(
            model_name='locationsnapshot',
            index=models.Index(fields=['location_name'], name='gbp_locatio_locatio_836f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationsnapshot',
            index=models.Index(fields=['business_name'], name='gbp_locatio_busines_6bb1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='locationsnapshot',
            index=models.Index(fields=['created_at'], name='gbp_locatio_created_23d7e8_idx'),
        ),
        migrations.AlterModelTable(
            name='fetchrun',
            table='gbp_fetchrun',
        ),
        migrations.AlterModelTable(
            name='locationsnapshot',
            table='gbp_locationsnapshot',
        ),
        migrations.AddIndex(
            model_name='masterlocation',
            index=models.Index(fields=['verification_status'], name='gbp_masterl_verific_21c27c_idx'),
        ),
        migrations.AddIndex(
            model_name='masterlocation',
            index=models.Index(fields=['network_name'], name='gbp_masterl_network_4aea54_idx'),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gbp.reconciliationjob', verbose_name='Job'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['job', 'process_status'], name='gbp_reconci_job_id_af3a70_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['job', 'status_changed'], name='gbp_reconci_job_id_899a56_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['store_code'], name='gbp_reconci_store_c_a48d93_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationresult',
            index=models.Index(fields=['business_name'], name='gbp_reconci_busines_3f2205_idx'),
        ),
    ]
