# Generated by Django 6.0.6 on 2026-06-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbp', '0002_masterlocation_reconciliationjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterlocation',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jenis Network'),
        ),
        migrations.AlterField(
            model_name='locationsnapshot',
            name='status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Duplicate', 'Duplicate'), ('Suspended', 'Suspended'), ('Need Verification', 'Need Verification'), ('Unverified', 'Unverified')], db_index=True, max_length=50, verbose_name='Status Verifikasi'),
        ),
    ]
