# Generated by Django 6.0.6 on 2026-06-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbp', '0003_masterlocation_area_masterlocation_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_network', models.IntegerField(default=0, verbose_name='Total Network')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Master Data History',
                'verbose_name_plural': 'Master Data Histories',
                'db_table': 'gbp_masterdatahistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
